name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh root@89.111.134.237 "cd /var/www/daisa.ru/abkhazia-frontend/ && git pull && npm install && npm run build && pm2 start npm --name daisa-frontend -- start && pm2 save"
